### ISSUE TITLE
Calendar Integration to front end using Acuity

### ISSUE THREAD

**Issue by maximdolphin** [AlephZ-ai/auto-scheduler#6]
```[tasklist]
### Tasks
- [ ] Test Acuity API in the front end to attempt to create schedules and get an understanding of the API
- [ ] Research all types of service appointments and add them as possibilities, using appointment dates same as Southern States Mazda Service hours.
- [ ] Add Acuity features into **typescript** front end that will allow for users to easily schedule service appointments
```

**Comment by maximdolphin** [comment]
Acuity API can be found here: https://developers.acuityscheduling.com/reference/quick-start
